### ISSUE TITLE
missing files?

### ISSUE THREAD

**Issue by Geczy** [chiefsmurph/pattern-predict#1]
Is this repo updated? 

`Error: Cannot find module './stock-fns/runOutlookAndTestsOnStockCSV'

**Comment by chiefsmurph** [comment]
you are right that this repo's index.js script is not currently working because of that line.  That function was deprecated at some point and now the two commands of interest are.

get todays outlook for all the stocks in stocksOfInterest.js

`node stock-fns/getTodaysOutlook --update`

run strategy testing for all stocks in stocksOfInterest.js

`node multi-core-strategy-testing/ --update`

I updated the readme with this, but ideally this repo gets to a place for index.js does something worthwhile.
